version: '3'

networks:
  stream-net:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - stream-net
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes

  nifi:
    image: apache/nifi:1.15.3
    restart: always
    hostname: nifi
    container_name: nifi
    ports:
      - 8080:8080
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=false
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      #- NIFI_WEB_PROXY_HOST=191.234.129.222:8080
    networks:
      - stream-net
    depends_on:
      - zookeeper
    volumes:
      - ./nifi/state:/opt/nifi/nifi-current/state
      - ./nifi/db:/opt/nifi/nifi-current/database_repository
      - ./nifi/flowfile:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi/content:/opt/nifi/nifi-current/content_repository
      - ./nifi/provenance:/opt/nifi/nifi-current/provenance_repository
      - ./nifi/logs:/opt/nifi/nifi-current/logs

  postgres:
    image: postgres:9.6.23
    restart: always
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - stream-net
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: metabase
      POSTGRES_DB: metabase
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  metabase-app:
    image: metabase/metabase:v0.40.3.1
    restart: always
    hostname: metabase
    container_name: metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: postgres
      MB_DB_HOST: postgres
    networks:
      - stream-net
    depends_on:
      - postgres
    links:
      - postgres
      
  minio:
    image: minio/minio:latest
    hostname: minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=aulafia 
      - MINIO_ROOT_PASSWORD=aulafia@123
    volumes:
      - ./minio/data:/data
      #- ./minio/land:/mnt/land
      #- ./minio/raw:/mnt/raw
      #- ./minio/context:/mnt/context
      #- ./minio/trusted:/mnt/trusted
    networks:
      - stream-net
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"

  hive:
    image: bde2020/hive
    hostname: hive
    container_name: hive
    networks:
      - stream-net
    ports:
      - 10000:10000

  hue:
    image: gethue/hue:latest
    hostname: hue
    container_name: hue
    networks:
      - stream-net
    ports:
      - 8888:8888
    volumes:
      - ./hue/hue.ini:/usr/share/hue/desktop/conf/hue.ini

  mysql:
    image: mysql:8.0.29
    hostname: mysql
    container_name: mysql
    command: --lower_case_table_names=1
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: aulafia@123
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
      MYSQL_DATABASE: hivedb
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 30
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - stream-net
